version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/orderbook"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/quoteservice"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
